/**
 * @author Guilherme Santana 60182
 * @author Pedro Fernandes 60694
 */
public enum Command {
    ADDPERSON, ADDSHOW, ADDPARTICIPATION, PREMIERE, REMOVESHOW, TAGSHOW, INFOSHOW, RATESHOW,
    INFOPERSON, LISTSHOWSPERSON, LISTPARTICIPATIONS, LISTBESTSHOWS, LISTSHOWS, LISTTAGGEDSHOWS,
    QUIT, UNKNOWN
}
